stages:
  get_data: 
    cmd: python src/data/make_dataset.py
    deps:
      - src/data/make_dataset.py
    outs:
      - data/raw/iris.csv

  process_data: 
    cmd: python src/data/process_data.py
    deps:
      - src/data/process_data.py
      - data/raw/iris.csv 
    outs:
      - data/processed/processed_iris.csv 

  train:
    cmd: python src/models/train_model.py
    deps:
      - src/models/train_model.py
      - data/processed/processed_iris.csv
      - params.yaml
    outs:
      - models/model.joblib