name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Poetry
        run: |
          pip install poetry

      - name: Install Dependencies
        run: |
          poetry install

      - name: Check Code Formatting with Black
        run: |
          poetry run black . --check

      - name: Set up DVC
        uses: iterative/setup-dvc@v2

      - name: Reproduce DVC Pipeline
        run: |
          poetry run dvc repro

      - name: Run Tests
        run: |
          poetry run pytest

# OPTIONAL IF NEED A DEPLOYMENT STEP

  # cd:
  #   needs: ci
  #   if: github.ref == 'refs/heads/main' && github.event_name == 'push'
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout Repository
  #       uses: actions/checkout@v5
  #       with:
  #         fetch-depth: 0

  #     - name: Log in to Docker Hub
  #       uses: docker/login-action@v3
  #       with:
  #         username: ${{ secrets.DOCKER_USERNAME }}
  #         password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

  #     - name: Build and Push Docker Image
  #       uses: docker/build-push-action@v5
  #       with:
  #         context: .
  #         push: true
  #         tags: ${{ secrets.DOCKER_USERNAME }}/mlops-template:latest
